### ISSUE TITLE
submit form

### ISSUE THREAD

**Issue by masihfathi** [Anorov/cloudflare-scrape#100]
thanks for your greate extension. is it possible to submit form with cloudflare protection? and how is it possible to post form?

**Comment by Xonshiz** [comment]
Which programming language are you using? Using this in python is pretty simple and straight forward. You could do something like this : 

```
import cfscrape
import requests

baseUrl = "https://www.webpage.com/login"

headers = {
            'User-Agent':
            'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36'
        }

payload = {
            'Data1': 'Value1',
            'Data2': 'Value2'
        }

sess = requests.session()
scraper = cfscrape.create_scraper(sess=session)
webPageResponse = sess.post(
            url=baseUrl,
            data=payload,
            headers=headers).text

print("This is the webpage's response : %s" % webPageResponse)

```

This should do the job just fine.
`sess` would contain your session info. And avoid used `session` named variable, because requests library has `session` method and it could get confusing.
