### ISSUE TITLE
I can't add user and password

### ISSUE THREAD

**Issue by alfilesnet** [Anorov/cloudflare-scrape#114]
I can't add user and password when I use cloudflare-scrape

Could you add it?

Thanks

**Comment by Anorov** [comment]
Please read the Requests documentation. Thanks.

On Aug 29, 2017 2:59 PM, "alfilesnet" <notifications@github.com> wrote:

I can't add user and password when I use cloudflare-scrape

Could you add it?

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Anorov/cloudflare-scrape/issues/114>, or mute the thread
