### ISSUE TITLE
is ok

### ISSUE THREAD

**Issue by liuzhaohui166** [Anorov/cloudflare-scrape#138]

**Comment by veteranbv** [comment]
Node.js is a required dependancy:

“Node.js is required for (safe) Javascript execution.
Your computer or server may already have it (check with node -v). If not, you can install it with apt-get install nodejs on Ubuntu and Debian. Otherwise, please read Node's installation instructions.”

If you already resolved this, please close the issue.

**Comment by architek** [comment]
Regarding this dependency, actually the Debian package **nodejs** only provides
/usr/bin/nodejs

In order to have /usr/bin/node you need to install **nodejs-legacy**, which is creates the symlink /usr/bin/node -> /usr/bin/nodejs.

Obviously, nodejs is a dependency of nodejs-legacy. 
So it is required to install nodejs-legacy and that should be sufficient. 

[Debian devel announce regarding namespace collision](https://lists.debian.org/debian-devel-announce/2012/07/msg00002.html)

**Comment by Anorov** [comment]
Updated the error message to advise users they may need to `apt-get install nodejs-legacy`.
