### ISSUE TITLE
TL search stopped working

### ISSUE THREAD

**Issue by Rudolf112** [Anorov/cloudflare-scrape#147]
2018-04-06 10:09:03 SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [1d34bcb] Request failed: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

Using latest version. Thanks!

**Comment by Hoveys** [comment]
im having the same issue with the same error code.  i've updated everything as well.  Anything else we can try?

**Comment by Hoveys** [comment]
"2018-04-06 09:05:41 SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [1d34bcb] Request failed: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script."

thats the exact error i'm getting.  i'm also getting this, but only once per reboot it seems 

"Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."
2018-04-06 08:40:54 ThreadPoolExecutor-0_0 :: [1d34bcb] Missing time zone for network: YouTube Red. Check valid network is set in indexer (theTVDB) before filing issue."

**Comment by Anorov** [comment]
Can you please confirm that the library you're using has the latest version of cfscrape? Try `pip install cfscrape -U`, and also try upgrading any packages you're using that rely on cfscrape ("TorrentLeech" perhaps, in this case? Not sure of the actual library you're using).

To confirm you're using the latest version, somewhere in your scraping code (or if you're using an existing script, you could add it somewhere in the `main()` function or anywhere else really) please add `print(cfscrape.__version__)`. The latest version of cloudflare-scrape is 1.9.5, so it should print `1.9.5`.

**Comment by pl77** [comment]
@Hoveys did you include the line `print("CFSCRAPE VERSION:", cfscrape.__version__)` in the python code where cfscrape was called?  If you're using sickrage, edit the following file: 
https://github.com/SickRage/SickRage/blob/1d34bcb48c1e03d568a8fdc08f60df8fa7f2d5d4/sickbeard/helpers.py#L1382

**Comment by Anorov** [comment]
Looks like SickRage's cfscrape requirement is specifying an old, incompatible version of cfscrape: https://github.com/SickRage/SickRage/blob/1d34bcb48c1e03d568a8fdc08f60df8fa7f2d5d4/requirements/requirements.txt#L10

`cfscrape == 1.7.1  # rq.filter: <1.8.0`

Locking it to a specific version is probably not a good idea, because any breaking changes Cloudflare makes will immediately cause that version of cfscrape to be completely non-functional.

It should probably be changed to:

`cfscrape >= 1.9.5`

Since this is in SickRage's hands and not actually due to a problem with cloudflare-scrape, I am closing this issue.
