### ISSUE TITLE
Unsecure code execution

### ISSUE THREAD

**Issue by ololoe** [Anorov/cloudflare-scrape#18]
execjs execs javascript code without a sandbox, which can lead to security issues. And you seem to simply exec javascript code from a page.

Example 

    import execjs

    default = execjs.get()
    default.exec_("""var fs = require('fs'); fs.unlinkSync('c:/asd');""")

deletes с:\asd

**Comment by Anorov** [comment]
This is prevented with the use of Node's `vm` module, which can sandbox code. See https://github.com/Anorov/cloudflare-scrape/blob/master/cfscrape/__init__.py#L39

I do not know enough about other JS engines to say for sure if arbitrary command execution is possible, which is why I have a warning at the bottom of the first block in the README. I recommend using Node, due to the specific sandboxing it provides, and also recommend using a VM or alternative low privilege environment.

Please tell me if you have any other concerns about this.

**Comment by ololoe** [comment]
What does line 38 mean

    if "Node" in execjs.get().name:

Does sandboxing work only with node.js?

    runInNewContext('%s')

Is it vulnerable to code injection like this?

    # js = "code'); mailicious_code();"
    runInNewContext('code');  mailicious_code();

**Comment by Anorov** [comment]
You're right, the code is completely insecure due to the straight string interpolation, with no validation or escaping. I don't think your proposed vector would work, since the return would short circuit it, but a simple injection of `', evil(), '` or similar would work fine.

Thankfully, the portion of Cloudflare's code responsible for the arithmetic does not use single quotes, so simply stripping all single quotes should make it impossible to escape the string context.

Thank you for spotting this.

And yes, right now sandboxing is only done for Node. I was unable to find ways of executing arbitrary code with V8 running locally. I don't know enough about other Javascript engines to determine if they're safe to use, so for now I'm going to restrict the runtimes to just Node and V8.

All changes have been made in this commit: https://github.com/Anorov/cloudflare-scrape/commit/0473b2ec722bb720199316a473a84e95b216dc46

Tell me if you have any other concerns.

**Comment by ne0ark** [comment]
This change had been pushed to pypi?

**Comment by Anorov** [comment]
@ne0ark Yes.

**Comment by Anorov** [comment]
Closing this for now. If anyone else has any concerns with this patch or method of sandboxing in Node, please reply here and/or open a new issue.

**Comment by ololoe** [comment]
I think you should disable all unsandboxed js engines by default, only allow it with something like "allow_unsecure" parameter.

**Comment by Anorov** [comment]
That depends how you define sandboxed.

Only V8 and Node are enabled at all, currently. Every other engine is disabled.

The V8 engine by default is "sandboxed" in that it has no standard lib, just the core Javascript runtime. IO and shell execution are not possible.

Node is not sandboxed, obviously, however the use of the `vm` module permits sandboxing so long as it is used correctly.
