### ISSUE TITLE
503 Server Error: Service Temporarily Unavailable token retrieval

### ISSUE THREAD

**Issue by quancore** [Anorov/cloudflare-scrape#183]
This issue mostly a question. I am getting 503 Server Error: Service Temporarily Unavailable in a random manner (by the way, It was working without failure like 2-3 weeks ago). I tried to increase the delay of scraper however, it did not decrease the rate of failure. What are the reasons for this behavior?

Links observed failures (I have many many more.These have been given for observation):
http://www.hltv.org/download/demo/46596
http://www.hltv.org/download/demo/46568
http://www.hltv.org/download/demo/46595

**Comment by quancore** [comment]
Need verification.

**Comment by Mattwmaster58** [comment]
I'm pretty certain that this has nothing to do with the waiting time between executing the challenge and submitting it. If you look at the response to the request, it turns out to be something like [this](https://screenshots.firefox.com/gP9PIyfPdukbdr8f/github.com)(CSS is probably wrong, but whatever).

You'll notice that this isn't the normal 'delaying' CF page. It's a straight up block. This case isn't mentioned anywhere in the readme, so I assume that there's no way around this right now.

PS If it was a delay issue, it could be fixed by specifying the delay time manually, ie `scraper = cfscrape.create_scraper(delay=10)`

**Comment by quancore** [comment]
Thanks for your response. When I try these pages to a browser, it works well. The strange thing is that If I would get a ban from the whole hltv, I could not reach any page, however, I can reach other pages. And also sometimes I retry a failed link again after a couple of time later, and it can work. Can you extend your answer to mimic my browser? I am working on a cloud with multiple instances so that just taking a sample and applying to all should not work. Should I update my user agent list maybe?

**Comment by quancore** [comment]
Waiting for a fix for rep. owner.

**Comment by quancore** [comment]
up.

**Comment by quancore** [comment]
up.

**Comment by Mattwmaster58** [comment]
Can you stop bumping this @quancore ?

**Comment by quancore** [comment]
Thank you for your answer. I have checked my code and decided that it is entirely related to the scraper. The thing is that it happens randomly and I cannot figure out why is happening. There would be wonderful to state a reason why this is happening?

**Comment by procknight** [comment]
You seem to misunderstand how this community works. Just because you think you found an issue does not mean everybody will stop what they are doing and work for your apparent issue.

If you can't find out whats wrong yourself and you don't get the answers you are looking for here, then hire someone who can.

Just because you can file an issue does not mean you have the right to get answer, real problem or not.


For people that would like to follow the project but are annoyed by this issue, you can ignore just this thread by unsubscribing from the specific issue.

**Comment by quancore** [comment]
First of all, it is obvious that I am not expecting that kind of reaction (everybody will stop what they are doing and work for your apparent issue) because I opened the issue 22 days ago and no solution or working advice happened and I am keep waiting as it should be.

I am sharing the important issue for me and I have no idea about whether it is a real problem or real issue that's why I always bump up the issue to get a valid answer.

And I am agreeing with your advice that if you do not have an idea for the solution, not faced with this issue or annoyed with messages, just unsubscribe it.

**Comment by Anorov** [comment]
Can you please try upgrading cloudflare-scrape with `pip install -U cfscrape` and see if you continue to experience this issue?
