### ISSUE TITLE
403 Responses with CAPTCHA

### ISSUE THREAD

**Issue by CalmLogarithm** [Anorov/cloudflare-scrape#190]
I'm scraping through a Tor connection.  But every request if its either get_tokens() or get() returns a 403 page with CAPTCHA.  When I browse to the site through a Tor browser I get right to the site without any CAPTCHA or 403.

My question is: **how can I debug cfscrape in order to better understand what is going wrong?**

My minimal functional code looks like:

`import cfscrape

proxies = {
   "http": "socks5h://localhost:9050",
   "https": "socks5h://localhost:9050"
}

url = "omitted"
tokens, user_agent = cfscrape.get_tokens(url, proxies=proxies)
print(tokens)`

**Comment by quancore** [comment]
There are several issues currently open for this problem. In my case, the server also returns captcha but in reality, it is not. Waiting for maintainers to handle if possible and feasible.

**Comment by CalmLogarithm** [comment]
[This page has a very close version](https://mopsshop24.biz.rega.city/sitemap.txt) of what I see.  So far my analysis is...

The script within "challenge-form" executes, passing the "data-ray" and "data-sitekey" parameters.  When it complete it'll generate a DOMContentLoaded event whose attributes include both the resulting hash and the time it took to complete.  These values are added as hidden input tags to the "challenge-form" form.  Although it's not immediately clear what is triggering the form submission.  Is it all the IFrame code?

**Comment by pro-src** [comment]
@CalmLogarithm, would you please create a pastebin with the response content so it can examined? Are you sure that there's a CAPTCHA with that 403 response and that particular response is from Cloudflare?

**Comment by CalmLogarithm** [comment]
@pro-src, [Here is the HTML ](https://pastebin.com/EiurvQXu) from the page in question.  Aside from the frequent "cf-*" names and use of "CloudFlare", it also references a CloudFlare domain in the JavaScript: ajax.cloudflare.com.  And there is a CAPTCHA, it is pulled from Google's domain for reCAPTCHA.

**Comment by pro-src** [comment]
@CalmLogarithm, since cloudflare-scrape is using the `requests` library and no exceptions are being raised, see this [stackoverflow page](https://stackoverflow.com/questions/10588644/how-can-i-see-the-entire-http-request-thats-being-sent-by-my-python-application) on how you might try to debug that. You'll want to identify the difference between the requests that are being made in those two environments. Use Tor Browser's [network monitor](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor). If you will put the requests and responses for each environment in their own pastebin, I'll review it for you.

**Comment by pro-src** [comment]
@CalmLogarithm, it's very possible that the only difference is the user agents. I would focus on the headers.

**Comment by CalmLogarithm** [comment]
@pro-src With this [Python requests log ](https://pastebin.com/0LLAKCFM) the problem is obviously the User-Agent string.  Looking at the cfscrape code the User-Agent should be randomly selected from the provided list.  Is there a quick work-around I should use in the mean time to specify my own User-Agent string?

**Comment by Mattwmaster58** [comment]
Yes. Since create_scraper returns an object that inherits from
requests.Session, simply initialize a scraper, ie by calling
create_scraper, and then set the user-agent dictionary key of the object's
headers attribute

**Comment by pro-src** [comment]
@Mattwmaster58 This definitely appears to be a bug because `get_tokens` is supposed to create an instance for you and override the user agent of that instance if the `user_agent` keyword argument is truthy. 

https://github.com/Anorov/cloudflare-scrape/blob/25e875509e46392bf0363b380951ce69319428cc/cfscrape/__init__.py#L173-L177

@CalmLogarithm What version of `requests` is being used? Your minimal code would be:
```py
`import cfscrape

proxies = {
"http": "socks5h://localhost:9050",
"https": "socks5h://localhost:9050"
}

url = "omitted"
user_agent = "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
tokens, user_agent = cfscrape.get_tokens(url, user_agent=user_agent, proxies=proxies)
print(tokens)`
```

**Comment by pro-src** [comment]
I'll try to get around to debugging this but I'm currently helping to develop https://github.com/codemanki/cloudscraper which is a port of cloudflare-scrape.

Let me know if passing the user agent to `get_tokens` doesn't solve this for you and I'll prioritize this issue.

**Comment by CalmLogarithm** [comment]
@Mattwmaster58 I can confirm that manually setting the User-Agent string via the session object works.  I was already passing a session object in order to specify proxies if that makes any difference.

**Comment by CalmLogarithm** [comment]
@pro-src The requests library version is 2.21.0.
