### ISSUE TITLE
Add requirements.txt and requirements-test.txt

### ISSUE THREAD

**Issue by fjovell** [Anorov/cloudflare-scrape#244]
As a python package it is very useful to have requirements.txt to automatically install requirements.

**Comment by pro-src** [comment]
Hi @fjovell 

It can be very useful but it isn't quite necessary for the package's dependencies because those dependencies are stored in `setup.py`. Pip knows how to install the package and doesn't use `requirements.txt`, you have to tell pip to use it. A lot of projects read that file on demand to copy it's contents whenever running setup.py.

For example, you can install the package and it's dependencies in either of these ways:
*  `pip install cfscrape`
*  `pip install -e .`

The latter of the two may be used when you've cloned the repo. Adding `requirements.txt` to store the dev-dependencies separately from the package's requirements is a valid use case and is conventional.

For that purpose, my preference is `requirements-dev.txt`. However, I prefer the use of Pipenv with Pipefile/Pipelock files over any `requirements.txt` since it makes the development environment more deterministic by locking all dependencies(inclusive of sub-dependencies) and uses a virtual environment. The project owner is in preference of using Pipenv as well.

Once you have a Pipefile, it's quite easy to generate a `requirements.txt` from it: https://docs.pipenv.org/en/latest/advanced/#generating-a-requirements-txt

`requirements.txt` could still be added although it would be more of a chore to keep it in sync.

You can expect this and other dev related configuration to be added to the repository soon. If you want to speed that up, PR's are welcome!

**Comment by fjovell** [comment]
Hi @pro-src, 

I just mentioned the requirements.txt as a way to quickly install requirements and test the package and since there is no information on the README I had thought I asked first. Probably a section at the end of the file to add these details you mentioned for possible contributors would be a fine addition.

**Comment by pro-src** [comment]
I'm working on a PR to add this stuff at this very moment. Once it lands, if you want to send a PR to document the dev workflow, I'm sure that would be welcomed. Is it okay to close this?

**Comment by fjovell** [comment]
That sounds great! you might as well add the documentation on the very same PR. Otherwise yes, it's okay to close.

**Comment by pro-src** [comment]
@fjovell https://github.com/Anorov/cloudflare-scrape/pull/246
