### ISSUE TITLE
CF de-protection does not work for mintos.com

### ISSUE THREAD

**Issue by soerenGer** [Anorov/cloudflare-scrape#287]
- [X] I've upgraded cfscrape with `pip install -U cfscrape` (=> total fresh install from today)
- [ ] I'm using Node version 10 or higher (=> v8.10.0, the doc says "greater 4.5" is sufficient? Installed from ubuntu-package)
- [X] The site protection I'm having issues with is from Cloudflare
- [X] I'm not using Tor, a VPN, or an anonymizing proxy

## Python version number

Run `python --version` and paste the output below:

```
Python 3.6.8
Running with virtual env on an ubuntu 18.04 LTS system
```

## cfscrape version number

Run `pip show cfscrape` and paste the output below:

```
Name: cfscrape
Version: 2.0.8
Summary: A simple Python module to bypass Cloudflare's anti-bot page. See https://github.com/Anorov/cloudflare-scrape for more information.
Home-page: https://github.com/Anorov/cloudflare-scrape
Author: Anorov
Author-email: anorov.vorona@gmail.com
License: UNKNOWN
Location: /storage/samba_familie/finanzen/p2p_lending/webimport/pyvenv/lib/python3.6/site-packages
Requires: requests
```

## Code snippet involved with the issue

```
import subprocess
import cfscrape

# See https://github.com/Anorov/cloudflare-scrape

# Use integration method

cookie_arg, user_agent = cfscrape.get_cookie_string("https://www.mintos.com")

print ("\n\n=== cookies ===\n\n")
print (cookie_arg)

print ("\n\n=== user_agent ===\n\n")
print (user_agent)

result = subprocess.check_output(["curl", "--cookie", cookie_arg, "-A", user_agent, "https://www.mintos.com/en/login"])

html_file = open("mintos_login.html", "w")
html_file.write(result.decode('utf-8'))
```

## Complete exception and traceback

(*If the problem doesn't involve an exception being raised, leave this blank*)

```

```

## URL of the Cloudflare-protected page

https://www.mintos.com

## URL of Pastebin/Gist with HTML source of protected page

[LINK GOES HERE]

Hi, I have just started with writing some scraping code for a certain website and wanted to use your library as the site uses CF. Have to say here, that there is a bunch of code for many non-CF protected sites already, but so far no python (which is still relativly new to me).

So what have I done so far:

- Created a virtualenv with python 3
- Installed your lib freshly
- adapted the small demo code to run with curl and created for debugging purpose the output of cookies and the resulting html file

It does not work, however I notice the following behaviour: Once the script runs it does not really wait but seems to continue almost immediately. So the normal "waiting behaviour" in the browser does not work in the script.
I can further see from the output, that the "cf_clearance" token is empty (afaik it should contain the "secret" value to overcome CF) and the resulting html file still shows the CF protection.
I am also not sure exactly about the usage of your lib. Please note that I try to get the cookies with the top page of the website and the try to get another ("/en/login") site of it. This works however for non CF-sites normally perfectly.

Another thing is that I noticed in the browser a slightly different behaviour of the CF protection since some days. It stays a very glimpse longer on the CF message the say a week ago or so, so may be they changed something recently; but not sure about this.

**Comment by pro-src** [comment]
Hi @soerenGer,

> Once the script runs it does not really wait but seems to continue almost immediately.

1. The URL that you're fetching to get the secret(cf_clearance) cookie doesn't have IUAM protection enabled. The second URL that you fetch does which is why you use the challenge response with curl.

> So the normal "waiting behaviour" in the browser does not work in the script.

See 1, the timeout is parsed from the challenge response. There is no protection on https://www.mintos.com thus no challenge response and no special handling. There is protection at the following location: https://www.mintos.com/en/login

> I can further see from the output, that the "cf_clearance" token is empty

The `get_cookie_string` method only raises an exception, if no cookies were found for the target URL. The same applies to `get_tokens` which is called by `get_cookie_string`. The `__cfduid` cookie is exists so you're not getting that error.

> and the resulting html file still shows the CF protection

The protection wasn't bypassed and the cf_clearance cookie is missing.

> Please note that I try to get the cookies with the top page of the website and the try to get another ("/en/login") site of it.

Just use cfscrape on "en/login" to get the unprotected HTML and/or cookies. I would recommend setting the referrer to the index page "/".

The simple solution here is to scrape a URL that has the protection enabled:
```sh
>>> cookie_arg, user_agent = cfscrape.get_cookie_string("https://www.mintos.com/en/login")
>>> cookie_arg
'__cfduid=d825f5a3d213648f2f5cb95ddf33c65821567764876; cf_clearance=e0f877c5533993617a8dc352c9281cb2b03e90ab-1567764880-1800-150'
>>> 
```

See https://github.com/Anorov/cloudflare-scrape/issues/286 for some relevant examples.

Cloudflare BIC(Browser Integrity Check) may detect the slightest change in the request headers, if you have issues with curl, reuse the exact same headers that cfscrape used to get the cookies, same header order, etc..

Cheers

**Comment by soerenGer** [comment]
Hi Dwayne,
thanks for pointing out some things I missed here. In fact I seem to have missed that only the /en/login has the protection, don't know why I have not seen this. As proposed with an additional "/en/login" in the initial request I now can see that both cookie values are generated and cfscrape works ,-) Very nice, thanks again !

**Comment by pro-src** [comment]
@soerenGer You're welcome, lmk if you have any other questions.
