### ISSUE TITLE
Javascriptless engine

### ISSUE THREAD

**Issue by ololoe** [Anorov/cloudflare-scrape#35]
I've made a regexp-only parser which doesn't need js engine and has no chance of mailicious code execution. It can also be more easily ported to other languages. Wanna to integrate it? You can keep existing js engines for a case if it stops working.

Here are 10 000 tests, you can check if they are passed correctly

https://cloud.githubusercontent.com/assets/5944139/11044957/03c6e9ae-8725-11e5-80ed-0c2533e4f7ad.png (rename to .rar and open)

**Comment by Anorov** [comment]
I appreciate the effort, but I think I'm going to have to decline. The nice part of a Javascript interpreter is that each time Cloudflare changes their code, it's pretty trivial to account for the new changes. With a regex, you may have to significantly modify your code, and if they're clever, they may someday make the challenge scripts dynamic enough that it's essentially impossible to parse properly without emulating the Javascript.

The security risks are nearly non-existent at the moment, because I restrict the Javascript engines to either plain V8, or sandboxed Node. Barring a critical exploit in either V8 or Node (which would greatly affect hundreds of thousands of other projects), the worst someone can do is a `while(true){}` and keep your process hanging forever. Someone could probably achieve the same effect with many regular expressions, by crafting a pathological string which the regex repeatedly backtracks on.

Admittedly, Cloudflare only seems to change their code about once a year on average, but that may change at any time, and I don't see the value in switching to a more crude form of parsing.

**Comment by ololoe** [comment]
I only made an expression evaluator which means I have to copy the rest from your project and then update it regularly. Or you can make some way to use it from your project instead of js engines.
