### ISSUE TITLE
[!] Unable to parse Cloudflare anti-bots page. 

### ISSUE THREAD

**Issue by Kunicboll** [Anorov/cloudflare-scrape#59]
I guess Cloudfare is updated, I tried to install newest version cfscrape, but still same error.cfscrape was working fine until a few days ago.

**Comment by Kunicboll** [comment]
others had already posted same issue

**Comment by Coriou** [comment]
It's been fixed in this [PR](https://github.com/Anorov/cloudflare-scrape/pull/57). PyPi might not be updated just yet though.

You can run `pip install git+git://github.com/Anorov/cloudflare-scrape` to install the latest version from Github (or `pip install git+git://github.com/Anorov/cloudflare-scrape --upgrade` to update an already installed version).

**Comment by Anorov** [comment]
New version is now on PyPI.
