### ISSUE TITLE
Better implementation

### ISSUE THREAD

**Issue by NitroXenon** [Anorov/cloudflare-scrape#62]
Here is the cloudflare bypassing module from SALTS (a kodi plugin). It seems to be a better implementation since it doesn't need any JavaScript engine.

Here is the code :
https://gist.github.com/NitroXenon/ddc338ca75f7f3a4bf587a5b3d92f5f4

**Comment by Anorov** [comment]
Please see my answer here: https://github.com/Anorov/cloudflare-scrape/issues/35#issuecomment-155678177

Especially with the recent change, it seems Cloudflare is more keen to change up their challenge now. This would mean effectively completely rewriting the expression evaluator for every significant change. Or, if they make the challenge generation very dynamic, it would mean a massive sprawlling codebase.

I'd even go so far as to argue that the fact we (and other libraries) using a JS interpreter might actually be discouraging Cloudflare from making very significant changes, since they realize how futile it would be. That might sound a little arrogant, but the change they made about 2 days ago seems to have directly been targeted at temporarily breaking this (or a very similar) library.

You can advertise this script as an alternative implementation for people who'd rather not use Node or PyV8 if you like, but I don't have any plans to change the current implementation.

**Comment by NitroXenon** [comment]
Okay thanks.
