### ISSUE TITLE
IP Banned because of VPN

### ISSUE THREAD

**Issue by nomanaliii** [Anorov/cloudflare-scrape#79]
Using a VPS (digital ocean) i tried to access kissmanga.com, Cloudflare banned IP saying "Disable the VPN". but i was on Virtual Private Server and using it's IP. 

![screen shot 2016-09-22 at 2 28 16 pm](https://cloud.githubusercontent.com/assets/13672261/18743078/d4c3efac-80d0-11e6-8235-d644e99e8d1d.png)

What's the solution to this thing?

PS: i was using it on my system and it was working perfectly alright then.

**Comment by Coriou** [comment]
Not really an issue with cfscrape, but here's an interesting read that might start answering your question : https://medium.com/@ValdikSS/detecting-vpn-and-its-configuration-and-proxy-users-on-the-server-side-1bcc59742413#.kjlxx2jdx

**Comment by nomanaliii** [comment]
Do you think there might be any solution to this problem? or can you suggest me a server that won't get its IP blocked with VPN issue,  where i can deploy my scraper? It would be great help.

Thanks in advance! :)

**Comment by Coriou** [comment]
Well the article I linked you provides quite in-depth explanations on how VPN / Proxies are detected. The author even set up a test page where you can see what your connection leaks (http://witch.valdikss.org.ru).

My advice is you take his advice and set-up your VPN program to mimic a home connection instead of blatantly showing up as a VPN to the site or CloudFlare (not sure which has implemented this VPN detection feature). I can't be sure, but I don't think every IP from Digital Ocean is blacklisted, otherwise they would have a different message than "Please try to disable your VPN".

**Comment by nomanaliii** [comment]
Not every IP is blacklisted, when i try with new VPS (Droplet) with a new IP, once it works but the 2nd time it get banned. i am noob to these VPS things. Don't know how to mimic home connection or whatever you mentioned :( sorry about that. but i'd really appreciate if you could get me through this problem.

**Comment by Coriou** [comment]
Yes most likely because the first time it notices you're a VPS then it blacklists the IP it so all future connections will fail (so they don't have to check if your connection is from a VPS every time which is a bit expensive).

Unfortunately you will have to figure it out yourself - or require help elsewhere. With that article I've sent you, you'll have everything you need to start researching though. I'm pretty sure you can succeed within a 1/2 day work tops. I'm not a network expert either myself and this is not the place to discuss this anyway as it really has nothing to do with this tool.

**Comment by nomanaliii** [comment]
Oh Thanks by the way. :)

**Comment by Anorov** [comment]
As already stated, this is not related to cloudflare-scrape. Cloudflare uses many different methods of determining if a visitor is a potential bot or attacker. cloudflare-scrape is only able to bypass the IUAM page and nothing more.
