### ISSUE TITLE
Getting the outerHTML

### ISSUE THREAD

**Issue by Xonshiz** [Anorov/cloudflare-scrape#89]
cfscrape is an amazing script and I've incorporated it in nearly all my projects. But, can we get the `outerHTML`? The HTML that's generated after the page is loaded. The one you see in the web dev console.

Currently we have to use PhantomJS to do so, which is quite heavy. It would be nice to have it in cfscrape.

**Comment by Anorov** [comment]
This is very much outside the scope of this project, sorry. The project's sole purpose is to provide seamless Cloudflare IUAM page bypassing.

I also don't understand how it would necessarily be any less heavy if it was in cfscrape, since I'd also have to add a ton of PhantomJS-like code.

Look into these projects:

* https://github.com/niklasb/dryscrape
* http://selenium-python.readthedocs.io/
* https://splinter.readthedocs.io/en/latest/
* http://jeanphix.me/Ghost.py/

You may need to use `cfscrape.get_tokens()` to integrate with them.
