### ISSUE TITLE
Not able to scrape sites.

### ISSUE THREAD

**Issue by anshuman91** [Anorov/cloudflare-scrape#96]
I am trying to request this site "http://misr365.com",  then I am getting <Response [403]>.
On opening the site in browser, I am getting Cloudflare page. Please find attached screenshot of browser page.
![screen shot 2017-02-26 at 1 36 44 am](https://cloud.githubusercontent.com/assets/3455354/23334416/0e369e24-fbc4-11e6-998a-fd17e25ac767.png)

>>> import cfscrape
>>> scraper = cfscrape.create_scraper()
>>> scraper.get("https://misr365.com")
<Response [403]>

**Comment by anshuman91** [comment]
I am running the latest version of this library.

**Comment by NitroXenon** [comment]
"Note: This only works when regular Cloudflare anti-bots is enabled (the "Checking your browser before accessing..." loading page). If there is a reCAPTCHA challenge, you're out of luck. Thankfully, the Javascript check page is much more common."

Did you read the README.md file?

**Comment by Anorov** [comment]
@anshuman91 please see @NitroXenon's response.

Cloudflare is likely flagging your IP address as a bot or attacker. Unfortunately, this library can't help with that. The easiest option would be to find an IP or proxy that isn't flagged. Otherwise, you'll have to manually solve the captcha and then pass the ID and clearance cookies to your script. (Like `scraper.cookies = {"__cfduid": "...", "cf_clearance": "..."}`).
